apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  template:
    spec:
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: ${PRODUCTION_VIDEO_STORAGE_CLAIM}
