apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-x-dependencies-config
  namespace: fiap-x
  labels:
    app.kubernetes.io/part-of: fiap-x
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: '3306'
  MYSQL_CONNECTION_LIMIT: '10'
  MYSQL_SSL: 'false'
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: '5672'
  PROMETHEUS_URL: http://prometheus:9090
  VIDEO_STORAGE_ROOT: /data/videos
