apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: fiap-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: fiap-x
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: fiap-x
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: fiap-x
    spec:
      hostname: rabbitmq
      securityContext:
        fsGroup: 999
      containers:
        - name: rabbitmq
          image: rabbitmq:4.1.4-management-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_NODENAME
              value: rabbit@rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: fiap-x-dependencies
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: fiap-x-dependencies
                  key: RABBITMQ_PASSWORD
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - check_running
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
