apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-storage
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: video-storage
    app.kubernetes.io/part-of: fiap-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
