apiVersion: v1
kind: Secret
metadata:
  name: fiap-x-application
  namespace: fiap-x
  labels:
    app.kubernetes.io/part-of: fiap-x
  annotations:
    fiap-x.io/example-only: 'true'
type: Opaque
stringData:
  AUTH_JWT_SECRET: REPLACE_WITH_AT_LEAST_32_RANDOM_BYTES
