apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: fiap-x
data:
  AUTH_HOST: 0.0.0.0
  AUTH_PORT: '3001'
  AUTH_JWT_EXPIRES_IN_SECONDS: '3600'
  AUTH_JWT_ISSUER: fiap-x-auth-service
  AUTH_JWT_AUDIENCE: fiap-x-api
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: fiap-x
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: '3001'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 3001
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fiap-x
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: fiap-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/part-of: fiap-x
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: auth-service
          image: fiap-x/auth-service:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fiap-x-dependencies-config
            - configMapRef:
                name: auth-service-config
          env:
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fiap-x-application
                  key: AUTH_JWT_SECRET
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fiap-x-dependencies
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-x-dependencies
                  key: MYSQL_PASSWORD
          ports:
            - name: http
              containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
