CREATE TABLE IF NOT EXISTS videos (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  extension VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  fps DECIMAL(10, 3) UNSIGNED NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  input_path VARCHAR(1024) NOT NULL,
  output_path VARCHAR(1024) NULL,
  error_message TEXT NULL,
  attempt INT UNSIGNED NOT NULL DEFAULT 1,
  processing_started_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY ix_videos_user_created (user_id, created_at DESC),
  KEY ix_videos_user_status (user_id, status),
  CONSTRAINT ck_videos_size CHECK (size_bytes > 0),
  CONSTRAINT ck_videos_fps CHECK (fps > 0),
  CONSTRAINT ck_videos_status CHECK (status IN ('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT ck_videos_attempt CHECK (attempt > 0)
) ENGINE=InnoDB;
